### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by DanielRuf** [splitline/PHPFuck#2]
It would be helpful to test this, also on PHP 5.x as far as possible.

**Comment by splitline** [comment]
Hi, does the `CI` you said means `continuous integration`? It's a good Idea, I will try it in my free time 😄 

btw, I don't think that this will work on PHP 5.x because of the following reason:
- Things like `'phpinfo'();` never works in PHP 5, you will just get a syntax error. But in my code need things like this to execute function. 😢 
- I want to support unicode characters like Chinese, Japanese, Emoji or something else, but it is a little tricky to do this  in php 5 😢
